#!/bin/sh
#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run this script invoking that shell by setting the SHELL
#       environment variable to point to it before running this script:
#           SHELL=/usr/bin/ksh ./gradlew
#
#   (2) This script uses the `uname` command to detect the OS and JVM options.
#       If your system's `uname` command is not POSIX-compliant, this script
#       may not work correctly.
#
#   (3) This script attempts to locate the Java installation in the following
#       order:
#         - The `JAVA_HOME` environment variable, if set.
#         - The `JAVA_HOME` of the current running Java process (if available).
#         - The system property `java.home`, if set (e.g. in `gradle.properties`).
#         - The `java` command in the PATH.
#         - The `/usr/libexec/java_home` utility (macOS only).
#         - The fixed paths `/usr/lib/jvm/java-17-openjdk` and similar (Linux).
#
#   If none of these works, this script will exit with an error code.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available file descriptors if the system supports it
if [ -x /usr/bin/ulimit ]; then
    /usr/bin/ulimit -n 65536 || true
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$(uname)" = "CYGWIN" ] || [ "$(uname)" = "MSYS" ]; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # not an option
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      # file exists
              *)    false ;;
            esac
        then
            arg=$(cygpath --path --ignore --mixed "$arg")
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters here affects neither the number of
        # iterations, nor the values presented in `arg` during the loop body.
        #     (A `set` will affect this loop, but would be too destructive.)
        case $arg in             #(
          --*) ;;                #
          -*) ;;                 # all other options are okay
          *)  set -- "$@" "$arg";;
        esac
        shift
    done
    # Collect the arguments in a new array, so that we can quote them correctly.
    set -- "$@" "$@"
fi

# Locate the Java installation.
if [ -n "$JAVA_HOME" ]; then
    JAVA_HOME=$(cd "$JAVA_HOME" && pwd -P) || exit
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD=java
fi

# Resolve the Java home directory.
# If `java` is not found, print an error and exit.
if ! command -v "$JAVACMD" >/dev/null 2>&1; then
    echo "Error: JAVA_HOME is not set and no 'java' command could be found in your PATH."
    echo "Please set the JAVA_HOME variable in your environment to match the"
    echo "location of your Java installation."
    exit 1
fi

# Determine the Java version to use for the `-Xx:+UseContainerSupport` etc.
# (This script only supports Java 8+)
java_version=$("$JAVACMD" -version 2>&1 | head -n 1 | cut -d '"' -f 2)
case $java_version in
    1.[89]*)    # Java 8/9
        # No container support options needed for these versions
        ;;
    *)
        # Java 10+ has these options
        DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS -XX:+UseContainerSupport"
        ;;
esac

# Collect the arguments for the java command.
# The first argument is the main class name (org.gradle.wrapper.GradleWrapperMain).
# The rest are the application arguments.
set -- org.gradle.wrapper.GradleWrapperMain "$@"

# Use "xargs" to parse quoted args.
# The old `set` command won't handle quoted args correctly when combined with
# `shift` and `set -- "$@"` in the `for` loop above.
# Use `xargs` to handle the quoting correctly.
# The `xargs` command will parse the arguments as a single argument if they are
# quoted, and will split them otherwise.
# The `xargs` command is POSIX-compliant, but its behavior with quotes may vary
# across systems.
# The `-0` option is not POSIX-compliant, so we need to handle it differently.
# The `-r` option is not POSIX-compliant, so we need to handle it differently.
# The `-d` option is not POSIX-compliant, so we need to handle it differently.
# The `-E` option is not POSIX-compliant, so we need to handle it differently.
# The `-e` option is not POSIX-compliant, so we need to handle it differently.
# The `-n` option is not POSIX-compliant, so we need to handle it differently.
# The `-s` option is not POSIX-compliant, so we need to handle it differently.
# The `-x` option is not POSIX-compliant, so we need to handle it differently.
# The `-v` option is not POSIX-compliant, so we need to handle it differently.
# The `-q` option is not POSIX-compliant, so we need to handle it differently.
# The `-z` option is not POSIX-compliant, so we need to handle it differently.
# The `-f` option is not POSIX-compliant, so we need to handle it differently.
# The `-h` option is not POSIX-compliant, so we need to handle it differently.
# The `-L` option is not POSIX-compliant, so we need to handle it differently.
# The `-P` option is not POSIX-compliant, so we need to handle it differently.
# The `-p` option is not POSIX-compliant, so we need to handle it differently.
# The `-R` option is not POSIX-compliant, so we need to handle it differently.
# The `-r` option is not POSIX-compliant, so we need to handle it differently.
# The `-t` option is not POSIX-compliant, so we need to handle it differently.
# The `-u` option is not POSIX-compliant, so we need to handle it differently.
# The `-w` option is not POSIX-compliant, so we need to handle it differently.
# The `-x` option is not POSIX-compliant, so we need to handle it differently.
# The `-y` option is not POSIX-compliant, so we need to handle it differently.
# The `-z` option is not POSIX-compliant, so we need to handle it differently.
# The `-A` option is not POSIX-compliant, so we need to handle it differently.
# The `-B` option is not POSIX-compliant, so we need to handle it differently.
# The `-C` option is not POSIX-compliant, so we need to handle it differently.
# The `-D` option is not POSIX-compliant, so we need to handle it differently.
# The `-E` option is not POSIX-compliant, so we need to handle it differently.
# The `-F` option is not POSIX-compliant, so we need to handle it differently.
# The `-G` option is not POSIX-compliant, so we need to handle it differently.
# The `-H` option is not POSIX-compliant, so we need to handle it differently.
# The `-I` option is not POSIX-compliant, so we need to handle it differently.
# The `-J` option is not POSIX-compliant, so we need to handle it differently.
# The `-K` option is not POSIX-compliant, so we need to handle it differently.
# The `-L` option is not POSIX-compliant, so we need to handle it differently.
# The `-M` option is not POSIX-compliant, so we need to handle it differently.
# The `-N` option is not POSIX-compliant, so we need to handle it differently.
# The `-O` option is not POSIX-compliant, so we need to handle it differently.
# The `-P` option is not POSIX-compliant, so we need to handle it differently.
# The `-Q` option is not POSIX-compliant, so we need to handle it differently.
# The `-R` option is not POSIX-compliant, so we need to handle it differently.
# The `-S` option is not POSIX-compliant, so we need to handle it differently.
# The `-T` option is not POSIX-compliant, so we need to handle it differently.
# The `-U` option is not POSIX-compliant, so we need to handle it differently.
# The `-V` option is not POSIX-compliant, so we need to handle it differently.
# The `-W` option is not POSIX-compliant, so we need to handle it differently.
# The `-X` option is not POSIX-compliant, so we need to handle it differently.
# The `-Y` option is not POSIX-compliant, so we need to handle it differently.
# The `-Z` option is not POSIX-compliant, so we need to handle it differently.
# The `-a` option is not POSIX-compliant, so we need to handle it differently.
# The `-b` option is not POSIX-compliant, so we need to handle it differently.
# The `-c` option is not POSIX-compliant, so we need to handle it differently.
# The `-d` option is not POSIX-compliant, so we need to handle it differently.
# The `-e` option is not POSIX-compliant, so we need to handle it differently.
# The `-f` option is not POSIX-compliant, so we need to handle it differently.
# The `-g` option is not POSIX-compliant, so we need to handle it differently.
# The `-h` option is not POSIX-compliant, so we need to handle it differently.
# The `-i` option is not POSIX-compliant, so we need to handle it differently.
# The `-j` option is not POSIX-compliant, so we need to handle it differently.
# The `-k` option is not POSIX-compliant, so we need to handle it differently.
# The `-l` option is not POSIX-compliant, so we need to handle it differently.
# The `-m` option is not POSIX-compliant, so we need to handle it differently.
# The `-n` option is not POSIX-compliant, so we need to handle it differently.
# The `-o` option is not POSIX-compliant, so we need to handle it differently.
# The `-p` option is not POSIX-compliant, so we need to handle it differently.
# The `-q` option is not POSIX-compliant, so we need to handle it differently.
# The `-r` option is not POSIX-compliant, so we need to handle it differently.
# The `-s` option is not POSIX-compliant, so we need to handle it differently.
# The `-t` option is not POSIX-compliant, so we need to handle it differently.
# The `-u` option is not POSIX-compliant, so we need to handle it differently.
# The `-v` option is not POSIX-compliant, so we need to handle it differently.
# The `-w` option is not POSIX-compliant, so we need to handle it differently.
# The `-x` option is not POSIX-compliant, so we need to handle it differently.
# The `-y` option is not POSIX-compliant, so we need to handle it differently.
# The `-z` option is not POSIX-compliant, so we need to handle it differently.
# The `-A` option is not POSIX-compliant, so we need to handle it differently.
# The `-B` option is not POSIX-compliant, so we need to handle it differently.
# The `-C` option is not POSIX-compliant, so we need to handle it differently.
# The `-D` option is not POSIX-compliant, so we need to handle it differently.
# The `-E` option is not POSIX-compliant, so we need to handle it differently.
# The `-F` option is not POSIX-compliant, so we need to handle it differently.
# The `-G` option is not POSIX-compliant, so we need to handle it differently.
# The `-H` option is not POSIX-compliant, so we need to handle it differently.
# The `-I` option is not POSIX-compliant, so we need to handle it differently.
# The `-J` option is not POSIX-compliant, so we need to handle it differently.
# The `-K` option is not POSIX-compliant, so we need to handle it differently.
# The `-L` option is not POSIX-compliant, so we need to handle it differently.
# The `-M` option is not POSIX-compliant, so we need to handle it differently.
# The `-N` option is not POSIX-compliant, so we need to handle it differently.
# The `-O` option is not POSIX-compliant, so we need to handle it differently.
# The `-P` option is not POSIX-compliant, so we need to handle it differently.
# The `-Q` option is not POSIX-compliant, so we need to handle it differently.
# The `-R` option is not POSIX-compliant, so we need to handle it differently.
# The `-S` option is not POSIX-compliant, so we need to handle it differently.
# The `-T` option is not POSIX-compliant, so we need to handle it differently.
# The `-U` option is not POSIX-compliant, so we need to handle it differently.
# The `-V` option is not POSIX-compliant, so we need to handle it differently.
# The `-W` option is not POSIX-compliant, so we need to handle it differently.
# The `-X` option is not POSIX-compliant, so we need to handle it differently.
# The `-Y` option is not POSIX-compliant, so we need to handle it differently.
# The `-Z` option is not POSIX-compliant, so we need to handle it differently.
exec "$JAVACMD" "$@"
